/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGslScopeProvider extends DelegatingScopeProvider {
}
