/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GslUiModule extends AbstractGslUiModule {

	public GslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
