/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GslRuntimeModule extends AbstractGslRuntimeModule {
}
