/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GslStandaloneSetup extends GslStandaloneSetupGenerated {

	public static void doSetup() {
		new GslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
