/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GamamodelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Gamamodel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGamamodelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cDescriptionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDescriptionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_2_1_0 = (RuleCall)cDescriptionAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cKeywordsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cKeywordsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cKeywordsEStringParserRuleCall_3_1_0 = (RuleCall)cKeywordsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAuthorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAuthorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_4_1_0 = (RuleCall)cAuthorAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCreatedOnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCreatedOnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCreatedOnEDateParserRuleCall_5_1_0 = (RuleCall)cCreatedOnAssignment_5_1.eContents().get(0);
		private final Keyword cContainsglobalKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cContainsglobalAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cContainsglobalGlobalBlockParserRuleCall_7_0 = (RuleCall)cContainsglobalAssignment_7.eContents().get(0);
		private final Keyword cContainsspecieKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cContainsspecieAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cContainsspecieSpecieBlockParserRuleCall_10_0 = (RuleCall)cContainsspecieAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cContainsspecieAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cContainsspecieSpecieBlockParserRuleCall_11_1_0 = (RuleCall)cContainsspecieAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cContainsexperimentKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cLeftCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cContainsexperimentAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cContainsexperimentExperimentBlockParserRuleCall_15_0 = (RuleCall)cContainsexperimentAssignment_15.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cCommaKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Assignment cContainsexperimentAssignment_16_1 = (Assignment)cGroup_16.eContents().get(1);
		private final RuleCall cContainsexperimentExperimentBlockParserRuleCall_16_1_0 = (RuleCall)cContainsexperimentAssignment_16_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//Gamamodel:
		//	'Gamamodel'
		//	'{' ('description' description=EString)? ('keywords' keywords=EString)? ('author' author=EString)? ('createdOn'
		//	createdOn=EDate)?
		//	'containsglobal' containsglobal=GlobalBlock
		//	'containsspecie' '{' containsspecie+=SpecieBlock ("," containsspecie+=SpecieBlock)* '}'
		//	'containsexperiment' '{' containsexperiment+=ExperimentBlock ("," containsexperiment+=ExperimentBlock)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Gamamodel' '{' ('description' description=EString)? ('keywords' keywords=EString)? ('author' author=EString)?
		//('createdOn' createdOn=EDate)? 'containsglobal' containsglobal=GlobalBlock 'containsspecie' '{'
		//containsspecie+=SpecieBlock ("," containsspecie+=SpecieBlock)* '}' 'containsexperiment' '{'
		//containsexperiment+=ExperimentBlock ("," containsexperiment+=ExperimentBlock)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Gamamodel'
		public Keyword getGamamodelKeyword_0() { return cGamamodelKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('description' description=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'description'
		public Keyword getDescriptionKeyword_2_0() { return cDescriptionKeyword_2_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_2_1() { return cDescriptionAssignment_2_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_2_1_0() { return cDescriptionEStringParserRuleCall_2_1_0; }
		
		//('keywords' keywords=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'keywords'
		public Keyword getKeywordsKeyword_3_0() { return cKeywordsKeyword_3_0; }
		
		//keywords=EString
		public Assignment getKeywordsAssignment_3_1() { return cKeywordsAssignment_3_1; }
		
		//EString
		public RuleCall getKeywordsEStringParserRuleCall_3_1_0() { return cKeywordsEStringParserRuleCall_3_1_0; }
		
		//('author' author=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'author'
		public Keyword getAuthorKeyword_4_0() { return cAuthorKeyword_4_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_4_1() { return cAuthorAssignment_4_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_4_1_0() { return cAuthorEStringParserRuleCall_4_1_0; }
		
		//('createdOn' createdOn=EDate)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'createdOn'
		public Keyword getCreatedOnKeyword_5_0() { return cCreatedOnKeyword_5_0; }
		
		//createdOn=EDate
		public Assignment getCreatedOnAssignment_5_1() { return cCreatedOnAssignment_5_1; }
		
		//EDate
		public RuleCall getCreatedOnEDateParserRuleCall_5_1_0() { return cCreatedOnEDateParserRuleCall_5_1_0; }
		
		//'containsglobal'
		public Keyword getContainsglobalKeyword_6() { return cContainsglobalKeyword_6; }
		
		//containsglobal=GlobalBlock
		public Assignment getContainsglobalAssignment_7() { return cContainsglobalAssignment_7; }
		
		//GlobalBlock
		public RuleCall getContainsglobalGlobalBlockParserRuleCall_7_0() { return cContainsglobalGlobalBlockParserRuleCall_7_0; }
		
		//'containsspecie'
		public Keyword getContainsspecieKeyword_8() { return cContainsspecieKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//containsspecie+=SpecieBlock
		public Assignment getContainsspecieAssignment_10() { return cContainsspecieAssignment_10; }
		
		//SpecieBlock
		public RuleCall getContainsspecieSpecieBlockParserRuleCall_10_0() { return cContainsspecieSpecieBlockParserRuleCall_10_0; }
		
		//("," containsspecie+=SpecieBlock)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//containsspecie+=SpecieBlock
		public Assignment getContainsspecieAssignment_11_1() { return cContainsspecieAssignment_11_1; }
		
		//SpecieBlock
		public RuleCall getContainsspecieSpecieBlockParserRuleCall_11_1_0() { return cContainsspecieSpecieBlockParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
		
		//'containsexperiment'
		public Keyword getContainsexperimentKeyword_13() { return cContainsexperimentKeyword_13; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_14() { return cLeftCurlyBracketKeyword_14; }
		
		//containsexperiment+=ExperimentBlock
		public Assignment getContainsexperimentAssignment_15() { return cContainsexperimentAssignment_15; }
		
		//ExperimentBlock
		public RuleCall getContainsexperimentExperimentBlockParserRuleCall_15_0() { return cContainsexperimentExperimentBlockParserRuleCall_15_0; }
		
		//("," containsexperiment+=ExperimentBlock)*
		public Group getGroup_16() { return cGroup_16; }
		
		//","
		public Keyword getCommaKeyword_16_0() { return cCommaKeyword_16_0; }
		
		//containsexperiment+=ExperimentBlock
		public Assignment getContainsexperimentAssignment_16_1() { return cContainsexperimentAssignment_16_1; }
		
		//ExperimentBlock
		public RuleCall getContainsexperimentExperimentBlockParserRuleCall_16_1_0() { return cContainsexperimentExperimentBlockParserRuleCall_16_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAction_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComplexeActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cReflexParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSimpleActionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Action:
		//	Action_Impl | ComplexeAction | Reflex | simpleAction;
		@Override public ParserRule getRule() { return rule; }
		
		//Action_Impl | ComplexeAction | Reflex | simpleAction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Action_Impl
		public RuleCall getAction_ImplParserRuleCall_0() { return cAction_ImplParserRuleCall_0; }
		
		//ComplexeAction
		public RuleCall getComplexeActionParserRuleCall_1() { return cComplexeActionParserRuleCall_1; }
		
		//Reflex
		public RuleCall getReflexParserRuleCall_2() { return cReflexParserRuleCall_2; }
		
		//simpleAction
		public RuleCall getSimpleActionParserRuleCall_3() { return cSimpleActionParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate ecore::EDate:
		//	'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	public class GlobalBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.GlobalBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInitAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cInitInitKeyword_0_0 = (Keyword)cInitAssignment_0.eContents().get(0);
		private final Keyword cGlobalBlockKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEIntParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cContainsglobalvariableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cContainsglobalvariableAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cContainsglobalvariableGlobalVariableParserRuleCall_6_0 = (RuleCall)cContainsglobalvariableAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cContainsglobalvariableAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cContainsglobalvariableGlobalVariableParserRuleCall_7_1_0 = (RuleCall)cContainsglobalvariableAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cHasspatialentityKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cHasspatialentityAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cHasspatialentitySpatialEntityParserRuleCall_11_0 = (RuleCall)cHasspatialentityAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cHasspatialentityAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cHasspatialentitySpatialEntityParserRuleCall_12_1_0 = (RuleCall)cHasspatialentityAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//GlobalBlock:
		//	init?='init'?
		//	'GlobalBlock'
		//	id=EInt
		//	'{'
		//	'containsglobalvariable' '{' containsglobalvariable+=GlobalVariable ("," containsglobalvariable+=GlobalVariable)* '}'
		//	'hasspatialentity' '{' hasspatialentity+=SpatialEntity ("," hasspatialentity+=SpatialEntity)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//init?='init'? 'GlobalBlock' id=EInt '{' 'containsglobalvariable' '{' containsglobalvariable+=GlobalVariable (","
		//containsglobalvariable+=GlobalVariable)* '}' 'hasspatialentity' '{' hasspatialentity+=SpatialEntity (","
		//hasspatialentity+=SpatialEntity)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//init?='init'?
		public Assignment getInitAssignment_0() { return cInitAssignment_0; }
		
		//'init'
		public Keyword getInitInitKeyword_0_0() { return cInitInitKeyword_0_0; }
		
		//'GlobalBlock'
		public Keyword getGlobalBlockKeyword_1() { return cGlobalBlockKeyword_1; }
		
		//id=EInt
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_0() { return cIdEIntParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'containsglobalvariable'
		public Keyword getContainsglobalvariableKeyword_4() { return cContainsglobalvariableKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//containsglobalvariable+=GlobalVariable
		public Assignment getContainsglobalvariableAssignment_6() { return cContainsglobalvariableAssignment_6; }
		
		//GlobalVariable
		public RuleCall getContainsglobalvariableGlobalVariableParserRuleCall_6_0() { return cContainsglobalvariableGlobalVariableParserRuleCall_6_0; }
		
		//("," containsglobalvariable+=GlobalVariable)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//containsglobalvariable+=GlobalVariable
		public Assignment getContainsglobalvariableAssignment_7_1() { return cContainsglobalvariableAssignment_7_1; }
		
		//GlobalVariable
		public RuleCall getContainsglobalvariableGlobalVariableParserRuleCall_7_1_0() { return cContainsglobalvariableGlobalVariableParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'hasspatialentity'
		public Keyword getHasspatialentityKeyword_9() { return cHasspatialentityKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//hasspatialentity+=SpatialEntity
		public Assignment getHasspatialentityAssignment_11() { return cHasspatialentityAssignment_11; }
		
		//SpatialEntity
		public RuleCall getHasspatialentitySpatialEntityParserRuleCall_11_0() { return cHasspatialentitySpatialEntityParserRuleCall_11_0; }
		
		//("," hasspatialentity+=SpatialEntity)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//hasspatialentity+=SpatialEntity
		public Assignment getHasspatialentityAssignment_12_1() { return cHasspatialentityAssignment_12_1; }
		
		//SpatialEntity
		public RuleCall getHasspatialentitySpatialEntityParserRuleCall_12_1_0() { return cHasspatialentitySpatialEntityParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class SpecieBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.SpecieBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAspectfunctionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cAspectfunctionAspectfunctionKeyword_0_0 = (Keyword)cAspectfunctionAssignment_0.eContents().get(0);
		private final Keyword cSpecieBlockKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSpecieBlockNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSpecieBlockNameEStringParserRuleCall_2_0 = (RuleCall)cSpecieBlockNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAspectNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAspectNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAspectNameEStringParserRuleCall_4_1_0 = (RuleCall)cAspectNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cColorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cColorAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cColorEStringParserRuleCall_5_1_0 = (RuleCall)cColorAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSkillofspecieKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSkillofspecieAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSkillofspecieEStringParserRuleCall_6_1_0 = (RuleCall)cSkillofspecieAssignment_6_1.eContents().get(0);
		private final Keyword cContainsactionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cContainsactionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cContainsactionActionParserRuleCall_9_0 = (RuleCall)cContainsactionAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cContainsactionAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cContainsactionActionParserRuleCall_10_1_0 = (RuleCall)cContainsactionAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cHaspropertieKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cHaspropertieAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cHaspropertiePropertieParserRuleCall_14_0 = (RuleCall)cHaspropertieAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cHaspropertieAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cHaspropertiePropertieParserRuleCall_15_1_0 = (RuleCall)cHaspropertieAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//SpecieBlock:
		//	aspectfunction?='aspectfunction'?
		//	'SpecieBlock'
		//	specieBlockName=EString
		//	'{' ('aspectName' aspectName=EString)? ('Color' Color=EString)? ('skillofspecie' skillofspecie=EString)?
		//	'containsaction' '{' containsaction+=Action ("," containsaction+=Action)* '}'
		//	'haspropertie' '{' haspropertie+=Propertie ("," haspropertie+=Propertie)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		////(initfunction?='initfunction')?
		//aspectfunction?='aspectfunction'? 'SpecieBlock' specieBlockName=EString '{' ('aspectName' aspectName=EString)? ('Color'
		//Color=EString)? ('skillofspecie' skillofspecie=EString)? 'containsaction' '{' containsaction+=Action (","
		//containsaction+=Action)* '}' 'haspropertie' '{' haspropertie+=Propertie ("," haspropertie+=Propertie)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		////(initfunction?='initfunction')?
		//aspectfunction?='aspectfunction'?
		public Assignment getAspectfunctionAssignment_0() { return cAspectfunctionAssignment_0; }
		
		//'aspectfunction'
		public Keyword getAspectfunctionAspectfunctionKeyword_0_0() { return cAspectfunctionAspectfunctionKeyword_0_0; }
		
		//'SpecieBlock'
		public Keyword getSpecieBlockKeyword_1() { return cSpecieBlockKeyword_1; }
		
		//specieBlockName=EString
		public Assignment getSpecieBlockNameAssignment_2() { return cSpecieBlockNameAssignment_2; }
		
		//EString
		public RuleCall getSpecieBlockNameEStringParserRuleCall_2_0() { return cSpecieBlockNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('aspectName' aspectName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'aspectName'
		public Keyword getAspectNameKeyword_4_0() { return cAspectNameKeyword_4_0; }
		
		//aspectName=EString
		public Assignment getAspectNameAssignment_4_1() { return cAspectNameAssignment_4_1; }
		
		//EString
		public RuleCall getAspectNameEStringParserRuleCall_4_1_0() { return cAspectNameEStringParserRuleCall_4_1_0; }
		
		//('Color' Color=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Color'
		public Keyword getColorKeyword_5_0() { return cColorKeyword_5_0; }
		
		//Color=EString
		public Assignment getColorAssignment_5_1() { return cColorAssignment_5_1; }
		
		//EString
		public RuleCall getColorEStringParserRuleCall_5_1_0() { return cColorEStringParserRuleCall_5_1_0; }
		
		//('skillofspecie' skillofspecie=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'skillofspecie'
		public Keyword getSkillofspecieKeyword_6_0() { return cSkillofspecieKeyword_6_0; }
		
		//skillofspecie=EString
		public Assignment getSkillofspecieAssignment_6_1() { return cSkillofspecieAssignment_6_1; }
		
		//EString
		public RuleCall getSkillofspecieEStringParserRuleCall_6_1_0() { return cSkillofspecieEStringParserRuleCall_6_1_0; }
		
		//'containsaction'
		public Keyword getContainsactionKeyword_7() { return cContainsactionKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//containsaction+=Action
		public Assignment getContainsactionAssignment_9() { return cContainsactionAssignment_9; }
		
		//Action
		public RuleCall getContainsactionActionParserRuleCall_9_0() { return cContainsactionActionParserRuleCall_9_0; }
		
		//("," containsaction+=Action)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//containsaction+=Action
		public Assignment getContainsactionAssignment_10_1() { return cContainsactionAssignment_10_1; }
		
		//Action
		public RuleCall getContainsactionActionParserRuleCall_10_1_0() { return cContainsactionActionParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'haspropertie'
		public Keyword getHaspropertieKeyword_12() { return cHaspropertieKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//haspropertie+=Propertie
		public Assignment getHaspropertieAssignment_14() { return cHaspropertieAssignment_14; }
		
		//Propertie
		public RuleCall getHaspropertiePropertieParserRuleCall_14_0() { return cHaspropertiePropertieParserRuleCall_14_0; }
		
		//("," haspropertie+=Propertie)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//haspropertie+=Propertie
		public Assignment getHaspropertieAssignment_15_1() { return cHaspropertieAssignment_15_1; }
		
		//Propertie
		public RuleCall getHaspropertiePropertieParserRuleCall_15_1_0() { return cHaspropertiePropertieParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class ExperimentBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.ExperimentBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExperimentBlockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExperimentNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExperimentNameEStringParserRuleCall_1_0 = (RuleCall)cExperimentNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Keyword cHasparameterKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHasparameterAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cHasparameterParameterParserRuleCall_6_0 = (RuleCall)cHasparameterAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cHasparameterAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cHasparameterParameterParserRuleCall_7_1_0 = (RuleCall)cHasparameterAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cHasoutputKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cHasoutputAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cHasoutputOutputParserRuleCall_11_0 = (RuleCall)cHasoutputAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cHasoutputAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cHasoutputOutputParserRuleCall_12_1_0 = (RuleCall)cHasoutputAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//ExperimentBlock:
		//	'ExperimentBlock'
		//	experimentName=EString
		//	'{' ('type' type=EString)?
		//	'hasparameter' '{' hasparameter+=Parameter ("," hasparameter+=Parameter)* '}'
		//	'hasoutput' '{' hasoutput+=Output ("," hasoutput+=Output)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ExperimentBlock' experimentName=EString '{' ('type' type=EString)? 'hasparameter' '{' hasparameter+=Parameter (","
		//hasparameter+=Parameter)* '}' 'hasoutput' '{' hasoutput+=Output ("," hasoutput+=Output)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'ExperimentBlock'
		public Keyword getExperimentBlockKeyword_0() { return cExperimentBlockKeyword_0; }
		
		//experimentName=EString
		public Assignment getExperimentNameAssignment_1() { return cExperimentNameAssignment_1; }
		
		//EString
		public RuleCall getExperimentNameEStringParserRuleCall_1_0() { return cExperimentNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('type' type=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'type'
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }
		
		//type=EString
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_3_1_0() { return cTypeEStringParserRuleCall_3_1_0; }
		
		//'hasparameter'
		public Keyword getHasparameterKeyword_4() { return cHasparameterKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//hasparameter+=Parameter
		public Assignment getHasparameterAssignment_6() { return cHasparameterAssignment_6; }
		
		//Parameter
		public RuleCall getHasparameterParameterParserRuleCall_6_0() { return cHasparameterParameterParserRuleCall_6_0; }
		
		//("," hasparameter+=Parameter)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//hasparameter+=Parameter
		public Assignment getHasparameterAssignment_7_1() { return cHasparameterAssignment_7_1; }
		
		//Parameter
		public RuleCall getHasparameterParameterParserRuleCall_7_1_0() { return cHasparameterParameterParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'hasoutput'
		public Keyword getHasoutputKeyword_9() { return cHasoutputKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//hasoutput+=Output
		public Assignment getHasoutputAssignment_11() { return cHasoutputAssignment_11; }
		
		//Output
		public RuleCall getHasoutputOutputParserRuleCall_11_0() { return cHasoutputOutputParserRuleCall_11_0; }
		
		//("," hasoutput+=Output)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//hasoutput+=Output
		public Assignment getHasoutputAssignment_12_1() { return cHasoutputAssignment_12_1; }
		
		//Output
		public RuleCall getHasoutputOutputParserRuleCall_12_1_0() { return cHasoutputOutputParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class GlobalVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.GlobalVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGlobalVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGlobalVariableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cGvarNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGvarNameEStringParserRuleCall_2_0 = (RuleCall)cGvarNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInitValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInitValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInitValueEStringParserRuleCall_5_1_0 = (RuleCall)cInitValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GlobalVariable:
		//	{GlobalVariable}
		//	'GlobalVariable'
		//	gvarName=EString
		//	'{' ('type' type=EString)? ('initValue' initValue=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{GlobalVariable} 'GlobalVariable' gvarName=EString '{' ('type' type=EString)? ('initValue' initValue=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{GlobalVariable}
		public Action getGlobalVariableAction_0() { return cGlobalVariableAction_0; }
		
		//'GlobalVariable'
		public Keyword getGlobalVariableKeyword_1() { return cGlobalVariableKeyword_1; }
		
		//gvarName=EString
		public Assignment getGvarNameAssignment_2() { return cGvarNameAssignment_2; }
		
		//EString
		public RuleCall getGvarNameEStringParserRuleCall_2_0() { return cGvarNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }
		
		//('initValue' initValue=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'initValue'
		public Keyword getInitValueKeyword_5_0() { return cInitValueKeyword_5_0; }
		
		//initValue=EString
		public Assignment getInitValueAssignment_5_1() { return cInitValueAssignment_5_1; }
		
		//EString
		public RuleCall getInitValueEStringParserRuleCall_5_1_0() { return cInitValueEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SpatialEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.SpatialEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSpatialEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSpatialEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cShapeNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cShapeNameEStringParserRuleCall_2_0 = (RuleCall)cShapeNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cShapePathKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cShapePathAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cShapePathEStringParserRuleCall_4_1_0 = (RuleCall)cShapePathAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SpatialEntity:
		//	{SpatialEntity}
		//	'SpatialEntity'
		//	shapeName=EString
		//	'{' ('shapePath' shapePath=EString)? ('type' type=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SpatialEntity} 'SpatialEntity' shapeName=EString '{' ('shapePath' shapePath=EString)? ('type' type=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{SpatialEntity}
		public Action getSpatialEntityAction_0() { return cSpatialEntityAction_0; }
		
		//'SpatialEntity'
		public Keyword getSpatialEntityKeyword_1() { return cSpatialEntityKeyword_1; }
		
		//shapeName=EString
		public Assignment getShapeNameAssignment_2() { return cShapeNameAssignment_2; }
		
		//EString
		public RuleCall getShapeNameEStringParserRuleCall_2_0() { return cShapeNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('shapePath' shapePath=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'shapePath'
		public Keyword getShapePathKeyword_4_0() { return cShapePathKeyword_4_0; }
		
		//shapePath=EString
		public Assignment getShapePathAssignment_4_1() { return cShapePathAssignment_4_1; }
		
		//EString
		public RuleCall getShapePathEStringParserRuleCall_4_1_0() { return cShapePathEStringParserRuleCall_4_1_0; }
		
		//('type' type=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=EString
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_5_1_0() { return cTypeEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Action_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Action_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActionNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActionNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActionNameEStringParserRuleCall_3_1_0 = (RuleCall)cActionNameAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Action_Impl Action:
		//	{Action}
		//	'Action'
		//	'{' ('actionName' actionName=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Action} 'Action' '{' ('actionName' actionName=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Action}
		public Action getActionAction_0() { return cActionAction_0; }
		
		//'Action'
		public Keyword getActionKeyword_1() { return cActionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('actionName' actionName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'actionName'
		public Keyword getActionNameKeyword_3_0() { return cActionNameKeyword_3_0; }
		
		//actionName=EString
		public Assignment getActionNameAssignment_3_1() { return cActionNameAssignment_3_1; }
		
		//EString
		public RuleCall getActionNameEStringParserRuleCall_3_1_0() { return cActionNameEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PropertieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Propertie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertieAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPropertieKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPropertieNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPropertieNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPropertieNameEStringParserRuleCall_3_1_0 = (RuleCall)cPropertieNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInitValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInitValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cInitValueEStringParserRuleCall_5_1_0 = (RuleCall)cInitValueAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Propertie:
		//	{Propertie}
		//	'Propertie'
		//	'{' ('propertieName' propertieName=EString)? ('type' type=EString)? ('initValue' initValue=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Propertie} 'Propertie' '{' ('propertieName' propertieName=EString)? ('type' type=EString)? ('initValue'
		//initValue=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Propertie}
		public Action getPropertieAction_0() { return cPropertieAction_0; }
		
		//'Propertie'
		public Keyword getPropertieKeyword_1() { return cPropertieKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('propertieName' propertieName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'propertieName'
		public Keyword getPropertieNameKeyword_3_0() { return cPropertieNameKeyword_3_0; }
		
		//propertieName=EString
		public Assignment getPropertieNameAssignment_3_1() { return cPropertieNameAssignment_3_1; }
		
		//EString
		public RuleCall getPropertieNameEStringParserRuleCall_3_1_0() { return cPropertieNameEStringParserRuleCall_3_1_0; }
		
		//('type' type=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }
		
		//('initValue' initValue=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'initValue'
		public Keyword getInitValueKeyword_5_0() { return cInitValueKeyword_5_0; }
		
		//initValue=EString
		public Assignment getInitValueAssignment_5_1() { return cInitValueAssignment_5_1; }
		
		//EString
		public RuleCall getInitValueEStringParserRuleCall_5_1_0() { return cInitValueEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ComplexeActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.ComplexeAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComplexeActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cComplexeActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEIntParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cActionNameEStringParserRuleCall_4_1_0 = (RuleCall)cActionNameAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ComplexeAction:
		//	{ComplexeAction}
		//	'ComplexeAction'
		//	id=EInt
		//	'{' ('actionName' actionName=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ComplexeAction} 'ComplexeAction' id=EInt '{' ('actionName' actionName=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{ComplexeAction}
		public Action getComplexeActionAction_0() { return cComplexeActionAction_0; }
		
		//'ComplexeAction'
		public Keyword getComplexeActionKeyword_1() { return cComplexeActionKeyword_1; }
		
		//id=EInt
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_0() { return cIdEIntParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('actionName' actionName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actionName'
		public Keyword getActionNameKeyword_4_0() { return cActionNameKeyword_4_0; }
		
		//actionName=EString
		public Assignment getActionNameAssignment_4_1() { return cActionNameAssignment_4_1; }
		
		//EString
		public RuleCall getActionNameEStringParserRuleCall_4_1_0() { return cActionNameEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ReflexElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Reflex");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cReflexAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReflexKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEIntParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cActionNameEStringParserRuleCall_4_1_0 = (RuleCall)cActionNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConditionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cConditionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cConditionEStringParserRuleCall_5_1_0 = (RuleCall)cConditionAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Reflex:
		//	{Reflex}
		//	'Reflex'
		//	id=EInt
		//	'{' ('actionName' actionName=EString)? ('condition' condition=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Reflex} 'Reflex' id=EInt '{' ('actionName' actionName=EString)? ('condition' condition=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Reflex}
		public Action getReflexAction_0() { return cReflexAction_0; }
		
		//'Reflex'
		public Keyword getReflexKeyword_1() { return cReflexKeyword_1; }
		
		//id=EInt
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_0() { return cIdEIntParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('actionName' actionName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actionName'
		public Keyword getActionNameKeyword_4_0() { return cActionNameKeyword_4_0; }
		
		//actionName=EString
		public Assignment getActionNameAssignment_4_1() { return cActionNameAssignment_4_1; }
		
		//EString
		public RuleCall getActionNameEStringParserRuleCall_4_1_0() { return cActionNameEStringParserRuleCall_4_1_0; }
		
		//('condition' condition=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'condition'
		public Keyword getConditionKeyword_5_0() { return cConditionKeyword_5_0; }
		
		//condition=EString
		public Assignment getConditionAssignment_5_1() { return cConditionAssignment_5_1; }
		
		//EString
		public RuleCall getConditionEStringParserRuleCall_5_1_0() { return cConditionEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SimpleActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.simpleAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSimpleActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSimpleActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdEIntParserRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cActionNameEStringParserRuleCall_4_1_0 = (RuleCall)cActionNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cReturnTypeEStringParserRuleCall_5_1_0 = (RuleCall)cReturnTypeAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//simpleAction:
		//	{simpleAction}
		//	'simpleAction'
		//	id=EInt
		//	'{' ('actionName' actionName=EString)? ('ReturnType' ReturnType=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{simpleAction} 'simpleAction' id=EInt '{' ('actionName' actionName=EString)? ('ReturnType' ReturnType=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{simpleAction}
		public Action getSimpleActionAction_0() { return cSimpleActionAction_0; }
		
		//'simpleAction'
		public Keyword getSimpleActionKeyword_1() { return cSimpleActionKeyword_1; }
		
		//id=EInt
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_2_0() { return cIdEIntParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('actionName' actionName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actionName'
		public Keyword getActionNameKeyword_4_0() { return cActionNameKeyword_4_0; }
		
		//actionName=EString
		public Assignment getActionNameAssignment_4_1() { return cActionNameAssignment_4_1; }
		
		//EString
		public RuleCall getActionNameEStringParserRuleCall_4_1_0() { return cActionNameEStringParserRuleCall_4_1_0; }
		
		//('ReturnType' ReturnType=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ReturnType'
		public Keyword getReturnTypeKeyword_5_0() { return cReturnTypeKeyword_5_0; }
		
		//ReturnType=EString
		public Assignment getReturnTypeAssignment_5_1() { return cReturnTypeAssignment_5_1; }
		
		//EString
		public RuleCall getReturnTypeEStringParserRuleCall_5_1_0() { return cReturnTypeEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParameterNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParameterNameEStringParserRuleCall_2_0 = (RuleCall)cParameterNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTargetVariableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTargetVariableAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTargetVariableEStringParserRuleCall_4_1_0 = (RuleCall)cTargetVariableAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter:
		//	{Parameter}
		//	'Parameter'
		//	parameterName=EString
		//	'{' ('targetVariable' targetVariable=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter} 'Parameter' parameterName=EString '{' ('targetVariable' targetVariable=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//parameterName=EString
		public Assignment getParameterNameAssignment_2() { return cParameterNameAssignment_2; }
		
		//EString
		public RuleCall getParameterNameEStringParserRuleCall_2_0() { return cParameterNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('targetVariable' targetVariable=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'targetVariable'
		public Keyword getTargetVariableKeyword_4_0() { return cTargetVariableKeyword_4_0; }
		
		//targetVariable=EString
		public Assignment getTargetVariableAssignment_4_1() { return cTargetVariableAssignment_4_1; }
		
		//EString
		public RuleCall getTargetVariableEStringParserRuleCall_4_1_0() { return cTargetVariableEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class OutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Output");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEIntParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOutputNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOutputNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOutputNameEStringParserRuleCall_3_1_0 = (RuleCall)cOutputNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFramerateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFramerateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFramerateEStringParserRuleCall_4_1_0 = (RuleCall)cFramerateAssignment_4_1.eContents().get(0);
		private final Keyword cHasdisplaysKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHasdisplaysAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cHasdisplaysDisplayParserRuleCall_7_0 = (RuleCall)cHasdisplaysAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cHasdisplaysAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cHasdisplaysDisplayParserRuleCall_8_1_0 = (RuleCall)cHasdisplaysAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cHasexportfileKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cHasexportfileAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cHasexportfileExportfileParserRuleCall_12_0 = (RuleCall)cHasexportfileAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cHasexportfileAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cHasexportfileExportfileParserRuleCall_13_1_0 = (RuleCall)cHasexportfileAssignment_13_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cHasmonitorKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cHasmonitorAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cHasmonitorMonitorParserRuleCall_17_0 = (RuleCall)cHasmonitorAssignment_17.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cCommaKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Assignment cHasmonitorAssignment_18_1 = (Assignment)cGroup_18.eContents().get(1);
		private final RuleCall cHasmonitorMonitorParserRuleCall_18_1_0 = (RuleCall)cHasmonitorAssignment_18_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//Output:
		//	'Output'
		//	id=EInt
		//	'{' ('outputName' outputName=EString)? ('framerate' framerate=EString)?
		//	'hasdisplays' '{' hasdisplays+=Display ("," hasdisplays+=Display)* '}'
		//	'hasexportfile' '{' hasexportfile+=Exportfile ("," hasexportfile+=Exportfile)* '}'
		//	'hasmonitor' '{' hasmonitor+=Monitor ("," hasmonitor+=Monitor)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Output' id=EInt '{' ('outputName' outputName=EString)? ('framerate' framerate=EString)? 'hasdisplays' '{'
		//hasdisplays+=Display ("," hasdisplays+=Display)* '}' 'hasexportfile' '{' hasexportfile+=Exportfile (","
		//hasexportfile+=Exportfile)* '}' 'hasmonitor' '{' hasmonitor+=Monitor ("," hasmonitor+=Monitor)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Output'
		public Keyword getOutputKeyword_0() { return cOutputKeyword_0; }
		
		//id=EInt
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EInt
		public RuleCall getIdEIntParserRuleCall_1_0() { return cIdEIntParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('outputName' outputName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'outputName'
		public Keyword getOutputNameKeyword_3_0() { return cOutputNameKeyword_3_0; }
		
		//outputName=EString
		public Assignment getOutputNameAssignment_3_1() { return cOutputNameAssignment_3_1; }
		
		//EString
		public RuleCall getOutputNameEStringParserRuleCall_3_1_0() { return cOutputNameEStringParserRuleCall_3_1_0; }
		
		//('framerate' framerate=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'framerate'
		public Keyword getFramerateKeyword_4_0() { return cFramerateKeyword_4_0; }
		
		//framerate=EString
		public Assignment getFramerateAssignment_4_1() { return cFramerateAssignment_4_1; }
		
		//EString
		public RuleCall getFramerateEStringParserRuleCall_4_1_0() { return cFramerateEStringParserRuleCall_4_1_0; }
		
		//'hasdisplays'
		public Keyword getHasdisplaysKeyword_5() { return cHasdisplaysKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//hasdisplays+=Display
		public Assignment getHasdisplaysAssignment_7() { return cHasdisplaysAssignment_7; }
		
		//Display
		public RuleCall getHasdisplaysDisplayParserRuleCall_7_0() { return cHasdisplaysDisplayParserRuleCall_7_0; }
		
		//("," hasdisplays+=Display)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//hasdisplays+=Display
		public Assignment getHasdisplaysAssignment_8_1() { return cHasdisplaysAssignment_8_1; }
		
		//Display
		public RuleCall getHasdisplaysDisplayParserRuleCall_8_1_0() { return cHasdisplaysDisplayParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'hasexportfile'
		public Keyword getHasexportfileKeyword_10() { return cHasexportfileKeyword_10; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//hasexportfile+=Exportfile
		public Assignment getHasexportfileAssignment_12() { return cHasexportfileAssignment_12; }
		
		//Exportfile
		public RuleCall getHasexportfileExportfileParserRuleCall_12_0() { return cHasexportfileExportfileParserRuleCall_12_0; }
		
		//("," hasexportfile+=Exportfile)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//hasexportfile+=Exportfile
		public Assignment getHasexportfileAssignment_13_1() { return cHasexportfileAssignment_13_1; }
		
		//Exportfile
		public RuleCall getHasexportfileExportfileParserRuleCall_13_1_0() { return cHasexportfileExportfileParserRuleCall_13_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//'hasmonitor'
		public Keyword getHasmonitorKeyword_15() { return cHasmonitorKeyword_15; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_16() { return cLeftCurlyBracketKeyword_16; }
		
		//hasmonitor+=Monitor
		public Assignment getHasmonitorAssignment_17() { return cHasmonitorAssignment_17; }
		
		//Monitor
		public RuleCall getHasmonitorMonitorParserRuleCall_17_0() { return cHasmonitorMonitorParserRuleCall_17_0; }
		
		//("," hasmonitor+=Monitor)*
		public Group getGroup_18() { return cGroup_18; }
		
		//","
		public Keyword getCommaKeyword_18_0() { return cCommaKeyword_18_0; }
		
		//hasmonitor+=Monitor
		public Assignment getHasmonitorAssignment_18_1() { return cHasmonitorAssignment_18_1; }
		
		//Monitor
		public RuleCall getHasmonitorMonitorParserRuleCall_18_1_0() { return cHasmonitorMonitorParserRuleCall_18_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}
	public class DisplayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Display");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDisplayKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDisplayNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDisplayNameEStringParserRuleCall_1_0 = (RuleCall)cDisplayNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDisplayTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDisplayTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDisplayTypeEStringParserRuleCall_3_1_0 = (RuleCall)cDisplayTypeAssignment_3_1.eContents().get(0);
		private final Keyword cSpecieblockKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSpecieblockAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSpecieblockSpecieBlockParserRuleCall_6_0 = (RuleCall)cSpecieblockAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSpecieblockAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSpecieblockSpecieBlockParserRuleCall_7_1_0 = (RuleCall)cSpecieblockAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Display:
		//	'Display'
		//	displayName=EString
		//	'{' ('displayType' displayType=EString)?
		//	'specieblock' '{' specieblock+=SpecieBlock ("," specieblock+=SpecieBlock)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Display' displayName=EString '{' ('displayType' displayType=EString)? 'specieblock' '{' specieblock+=SpecieBlock (","
		//specieblock+=SpecieBlock)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Display'
		public Keyword getDisplayKeyword_0() { return cDisplayKeyword_0; }
		
		//displayName=EString
		public Assignment getDisplayNameAssignment_1() { return cDisplayNameAssignment_1; }
		
		//EString
		public RuleCall getDisplayNameEStringParserRuleCall_1_0() { return cDisplayNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('displayType' displayType=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'displayType'
		public Keyword getDisplayTypeKeyword_3_0() { return cDisplayTypeKeyword_3_0; }
		
		//displayType=EString
		public Assignment getDisplayTypeAssignment_3_1() { return cDisplayTypeAssignment_3_1; }
		
		//EString
		public RuleCall getDisplayTypeEStringParserRuleCall_3_1_0() { return cDisplayTypeEStringParserRuleCall_3_1_0; }
		
		//'specieblock'
		public Keyword getSpecieblockKeyword_4() { return cSpecieblockKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//specieblock+=SpecieBlock
		public Assignment getSpecieblockAssignment_6() { return cSpecieblockAssignment_6; }
		
		//SpecieBlock
		public RuleCall getSpecieblockSpecieBlockParserRuleCall_6_0() { return cSpecieblockSpecieBlockParserRuleCall_6_0; }
		
		//("," specieblock+=SpecieBlock)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//specieblock+=SpecieBlock
		public Assignment getSpecieblockAssignment_7_1() { return cSpecieblockAssignment_7_1; }
		
		//SpecieBlock
		public RuleCall getSpecieblockSpecieBlockParserRuleCall_7_1_0() { return cSpecieblockSpecieBlockParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ExportfileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Exportfile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExportfileAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExportfileKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFileNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFileNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFileNameEStringParserRuleCall_3_1_0 = (RuleCall)cFileNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFileTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFileTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFileTypeEStringParserRuleCall_4_1_0 = (RuleCall)cFileTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Exportfile:
		//	{Exportfile}
		//	'Exportfile'
		//	'{' ('fileName' fileName=EString)? ('fileType' fileType=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Exportfile} 'Exportfile' '{' ('fileName' fileName=EString)? ('fileType' fileType=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Exportfile}
		public Action getExportfileAction_0() { return cExportfileAction_0; }
		
		//'Exportfile'
		public Keyword getExportfileKeyword_1() { return cExportfileKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('fileName' fileName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'fileName'
		public Keyword getFileNameKeyword_3_0() { return cFileNameKeyword_3_0; }
		
		//fileName=EString
		public Assignment getFileNameAssignment_3_1() { return cFileNameAssignment_3_1; }
		
		//EString
		public RuleCall getFileNameEStringParserRuleCall_3_1_0() { return cFileNameEStringParserRuleCall_3_1_0; }
		
		//('fileType' fileType=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fileType'
		public Keyword getFileTypeKeyword_4_0() { return cFileTypeKeyword_4_0; }
		
		//fileType=EString
		public Assignment getFileTypeAssignment_4_1() { return cFileTypeAssignment_4_1; }
		
		//EString
		public RuleCall getFileTypeEStringParserRuleCall_4_1_0() { return cFileTypeEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class MonitorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ktsv.gsl.Gsl.Monitor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMonitorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMonitorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelEStringParserRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTargetVarKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTargetVarAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTargetVarEStringParserRuleCall_4_1_0 = (RuleCall)cTargetVarAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Monitor:
		//	{Monitor}
		//	'Monitor'
		//	label=EString
		//	'{' ('targetVar' targetVar=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Monitor} 'Monitor' label=EString '{' ('targetVar' targetVar=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Monitor}
		public Action getMonitorAction_0() { return cMonitorAction_0; }
		
		//'Monitor'
		public Keyword getMonitorKeyword_1() { return cMonitorKeyword_1; }
		
		//label=EString
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }
		
		//EString
		public RuleCall getLabelEStringParserRuleCall_2_0() { return cLabelEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('targetVar' targetVar=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'targetVar'
		public Keyword getTargetVarKeyword_4_0() { return cTargetVarKeyword_4_0; }
		
		//targetVar=EString
		public Assignment getTargetVarAssignment_4_1() { return cTargetVarAssignment_4_1; }
		
		//EString
		public RuleCall getTargetVarEStringParserRuleCall_4_1_0() { return cTargetVarEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final GamamodelElements pGamamodel;
	private final ActionElements pAction;
	private final EStringElements pEString;
	private final EDateElements pEDate;
	private final GlobalBlockElements pGlobalBlock;
	private final SpecieBlockElements pSpecieBlock;
	private final ExperimentBlockElements pExperimentBlock;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final GlobalVariableElements pGlobalVariable;
	private final SpatialEntityElements pSpatialEntity;
	private final Action_ImplElements pAction_Impl;
	private final PropertieElements pPropertie;
	private final ComplexeActionElements pComplexeAction;
	private final ReflexElements pReflex;
	private final SimpleActionElements pSimpleAction;
	private final ParameterElements pParameter;
	private final OutputElements pOutput;
	private final DisplayElements pDisplay;
	private final ExportfileElements pExportfile;
	private final MonitorElements pMonitor;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGamamodel = new GamamodelElements();
		this.pAction = new ActionElements();
		this.pEString = new EStringElements();
		this.pEDate = new EDateElements();
		this.pGlobalBlock = new GlobalBlockElements();
		this.pSpecieBlock = new SpecieBlockElements();
		this.pExperimentBlock = new ExperimentBlockElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.pGlobalVariable = new GlobalVariableElements();
		this.pSpatialEntity = new SpatialEntityElements();
		this.pAction_Impl = new Action_ImplElements();
		this.pPropertie = new PropertieElements();
		this.pComplexeAction = new ComplexeActionElements();
		this.pReflex = new ReflexElements();
		this.pSimpleAction = new SimpleActionElements();
		this.pParameter = new ParameterElements();
		this.pOutput = new OutputElements();
		this.pDisplay = new DisplayElements();
		this.pExportfile = new ExportfileElements();
		this.pMonitor = new MonitorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.ktsv.gsl.Gsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Gamamodel:
	//	'Gamamodel'
	//	'{' ('description' description=EString)? ('keywords' keywords=EString)? ('author' author=EString)? ('createdOn'
	//	createdOn=EDate)?
	//	'containsglobal' containsglobal=GlobalBlock
	//	'containsspecie' '{' containsspecie+=SpecieBlock ("," containsspecie+=SpecieBlock)* '}'
	//	'containsexperiment' '{' containsexperiment+=ExperimentBlock ("," containsexperiment+=ExperimentBlock)* '}'
	//	'}';
	public GamamodelElements getGamamodelAccess() {
		return pGamamodel;
	}
	
	public ParserRule getGamamodelRule() {
		return getGamamodelAccess().getRule();
	}
	
	//Action:
	//	Action_Impl | ComplexeAction | Reflex | simpleAction;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDate ecore::EDate:
	//	'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//GlobalBlock:
	//	init?='init'?
	//	'GlobalBlock'
	//	id=EInt
	//	'{'
	//	'containsglobalvariable' '{' containsglobalvariable+=GlobalVariable ("," containsglobalvariable+=GlobalVariable)* '}'
	//	'hasspatialentity' '{' hasspatialentity+=SpatialEntity ("," hasspatialentity+=SpatialEntity)* '}'
	//	'}';
	public GlobalBlockElements getGlobalBlockAccess() {
		return pGlobalBlock;
	}
	
	public ParserRule getGlobalBlockRule() {
		return getGlobalBlockAccess().getRule();
	}
	
	//SpecieBlock:
	//	aspectfunction?='aspectfunction'?
	//	'SpecieBlock'
	//	specieBlockName=EString
	//	'{' ('aspectName' aspectName=EString)? ('Color' Color=EString)? ('skillofspecie' skillofspecie=EString)?
	//	'containsaction' '{' containsaction+=Action ("," containsaction+=Action)* '}'
	//	'haspropertie' '{' haspropertie+=Propertie ("," haspropertie+=Propertie)* '}'
	//	'}';
	public SpecieBlockElements getSpecieBlockAccess() {
		return pSpecieBlock;
	}
	
	public ParserRule getSpecieBlockRule() {
		return getSpecieBlockAccess().getRule();
	}
	
	//ExperimentBlock:
	//	'ExperimentBlock'
	//	experimentName=EString
	//	'{' ('type' type=EString)?
	//	'hasparameter' '{' hasparameter+=Parameter ("," hasparameter+=Parameter)* '}'
	//	'hasoutput' '{' hasoutput+=Output ("," hasoutput+=Output)* '}'
	//	'}';
	public ExperimentBlockElements getExperimentBlockAccess() {
		return pExperimentBlock;
	}
	
	public ParserRule getExperimentBlockRule() {
		return getExperimentBlockAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//GlobalVariable:
	//	{GlobalVariable}
	//	'GlobalVariable'
	//	gvarName=EString
	//	'{' ('type' type=EString)? ('initValue' initValue=EString)?
	//	'}';
	public GlobalVariableElements getGlobalVariableAccess() {
		return pGlobalVariable;
	}
	
	public ParserRule getGlobalVariableRule() {
		return getGlobalVariableAccess().getRule();
	}
	
	//SpatialEntity:
	//	{SpatialEntity}
	//	'SpatialEntity'
	//	shapeName=EString
	//	'{' ('shapePath' shapePath=EString)? ('type' type=EString)?
	//	'}';
	public SpatialEntityElements getSpatialEntityAccess() {
		return pSpatialEntity;
	}
	
	public ParserRule getSpatialEntityRule() {
		return getSpatialEntityAccess().getRule();
	}
	
	//Action_Impl Action:
	//	{Action}
	//	'Action'
	//	'{' ('actionName' actionName=EString)?
	//	'}';
	public Action_ImplElements getAction_ImplAccess() {
		return pAction_Impl;
	}
	
	public ParserRule getAction_ImplRule() {
		return getAction_ImplAccess().getRule();
	}
	
	//Propertie:
	//	{Propertie}
	//	'Propertie'
	//	'{' ('propertieName' propertieName=EString)? ('type' type=EString)? ('initValue' initValue=EString)?
	//	'}';
	public PropertieElements getPropertieAccess() {
		return pPropertie;
	}
	
	public ParserRule getPropertieRule() {
		return getPropertieAccess().getRule();
	}
	
	//ComplexeAction:
	//	{ComplexeAction}
	//	'ComplexeAction'
	//	id=EInt
	//	'{' ('actionName' actionName=EString)?
	//	'}';
	public ComplexeActionElements getComplexeActionAccess() {
		return pComplexeAction;
	}
	
	public ParserRule getComplexeActionRule() {
		return getComplexeActionAccess().getRule();
	}
	
	//Reflex:
	//	{Reflex}
	//	'Reflex'
	//	id=EInt
	//	'{' ('actionName' actionName=EString)? ('condition' condition=EString)?
	//	'}';
	public ReflexElements getReflexAccess() {
		return pReflex;
	}
	
	public ParserRule getReflexRule() {
		return getReflexAccess().getRule();
	}
	
	//simpleAction:
	//	{simpleAction}
	//	'simpleAction'
	//	id=EInt
	//	'{' ('actionName' actionName=EString)? ('ReturnType' ReturnType=EString)?
	//	'}';
	public SimpleActionElements getSimpleActionAccess() {
		return pSimpleAction;
	}
	
	public ParserRule getSimpleActionRule() {
		return getSimpleActionAccess().getRule();
	}
	
	//Parameter:
	//	{Parameter}
	//	'Parameter'
	//	parameterName=EString
	//	'{' ('targetVariable' targetVariable=EString)?
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Output:
	//	'Output'
	//	id=EInt
	//	'{' ('outputName' outputName=EString)? ('framerate' framerate=EString)?
	//	'hasdisplays' '{' hasdisplays+=Display ("," hasdisplays+=Display)* '}'
	//	'hasexportfile' '{' hasexportfile+=Exportfile ("," hasexportfile+=Exportfile)* '}'
	//	'hasmonitor' '{' hasmonitor+=Monitor ("," hasmonitor+=Monitor)* '}'
	//	'}';
	public OutputElements getOutputAccess() {
		return pOutput;
	}
	
	public ParserRule getOutputRule() {
		return getOutputAccess().getRule();
	}
	
	//Display:
	//	'Display'
	//	displayName=EString
	//	'{' ('displayType' displayType=EString)?
	//	'specieblock' '{' specieblock+=SpecieBlock ("," specieblock+=SpecieBlock)* '}'
	//	'}';
	public DisplayElements getDisplayAccess() {
		return pDisplay;
	}
	
	public ParserRule getDisplayRule() {
		return getDisplayAccess().getRule();
	}
	
	//Exportfile:
	//	{Exportfile}
	//	'Exportfile'
	//	'{' ('fileName' fileName=EString)? ('fileType' fileType=EString)?
	//	'}';
	public ExportfileElements getExportfileAccess() {
		return pExportfile;
	}
	
	public ParserRule getExportfileRule() {
		return getExportfileAccess().getRule();
	}
	
	//Monitor:
	//	{Monitor}
	//	'Monitor'
	//	label=EString
	//	'{' ('targetVar' targetVar=EString)?
	//	'}';
	public MonitorElements getMonitorAccess() {
		return pMonitor;
	}
	
	public ParserRule getMonitorRule() {
		return getMonitorAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
