/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl.ui;

import com.google.inject.Injector;
import com.ktsv.gsl.ui.internal.GslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GslActivator activator = GslActivator.getInstance();
		return activator != null ? activator.getInjector(GslActivator.COM_KTSV_GSL_GSL) : null;
	}

}
