/*
 * generated by Xtext 2.21.0
 */
package com.ktsv.gsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.ktsv.gsl.GslRuntimeModule;
import com.ktsv.gsl.GslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GslIdeSetup extends GslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GslRuntimeModule(), new GslIdeModule()));
	}
	
}
